kind: pipeline
name: main

steps:
- name: git-submodules
  image: docker:git
  commands:
  - git submodule update --recursive --remote

# - name: build
#   image: pfillion/drone-dind
#   volumes:
#   - name: docker_volume
#     path: /var/run
#   commands:
#   - make build
#   - make VERSION=10.3 build
#   - make VERSION=10.1 build

- name: test
  image: pfillion/drone-dind
  volumes:
  - name: docker_volume
    path: /var/run
  commands:
  - ls -lahR test/test_helper/
  # - make test
  # - make VERSION=10.3 test
  # - make VERSION=10.1 test

# - name: docker-push
#   image: pfillion/drone-dind
#   volumes:
#   - name: docker_volume
#     path: /var/run
#   environment:
#     DOCKER_USERNAME:
#       from_secret: docker_username
#     DOCKER_PASSWORD:
#       from_secret: docker_password
#   commands:
#   - make docker-push
#   - make VERSION=10.3 docker-push
#   - make VERSION=10.1 docker-push

# - name: notify-microbadger
#   image: plugins/webhook
#   settings:
#     urls:
#       from_secret: webhook_urls

services:
- name: docker
  image: pfillion/drone-dind
  privileged: true
  volumes:
  - name: docker_volume
    path: /var/run

volumes:
- name: docker_volume
  temp: {}